Code/ThreeMicro/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ThreeMicro.views.home', name='home'),
    # url(r'^ThreeMicro/', include('ThreeMicro.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

Code/activity/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('activity.views',
    # for student
    # url(r'^$', 'showActivities', {'templateName' : 'activities.html'}),
    url(r'^student/$', 'showActivityIndex', {'templateName' : 'microStudent.html'}),
    url(r'^waiting/$', 'showWaitingActivity', {'templateName' : 'microActivityState.html'}),
    url(r'^complete/$', 'getCompleteActivities', {'templateName' : 'microPersonalGain.html'}), # for ajax
    url(r'^registing/$', 'getRegistingActivities', {'templateName' : 'microAttendedActivity.html'}), # for ajax
    url(r'^applied/$', 'getAppliedActivities', {'templateName' : 'microApplyedActivity.html'}),
    url(r'^campus/$', 'getCampus', {'templateName' : 'microLatestActivity.html'}),
    url(r'^campus/(\w+)/$', 'getOneCampusActivity', {'templateName' : 'microCampusActivity.html'}),
    url(r'^campus/complete/(\w+)/$', 'getOneCampusCompleteActivity', {'templateName': 'microCampusActivity.html'}),
    url(r'^registrants/(\d+)/$', 'showActivityRegistrant', {'templateName' : 'microAttendedPeople.html'}),
    url(r'^sign/$', 'signActivity'), # for ajax
    url(r'^signIn/$', 'signInActivity'), # for ajax
    url(r'^signOut/$', 'signOutActivity'), # for ajax
    url(r'^allSignIn/$', 'oneKeyToSignIn'), # for ajax
    url(r'^allSignOut/$', 'oneKeyToSignOut'), # for ajax
    url(r'^comfirm/$', 'comfirmActivityEnd'), # for ajax
    url(r'^cancel/$', 'cancelSignActivity'), # for ajax
    url(r'^getAvailableLocation/$', 'getAvailableLocation'), # for ajax
    url(r'^getAvailableNumber/$', 'getAvailableNumber'), # for ajax

    # for teacher and committee
    url(r'^examine/$', 'showMicroApplying', {'templateName' : 'microAssessActivity.html'}),
    url(r'^pass/$', 'examineActivity'), # for ajax

    # for all
    url(r'^microApply/$', 'assignViewer'),
    url(r'^sdetail/(\d+)/$', 'showActivityDetail', {'templateName' : 'microActivityDetail.html'}),
    url(r'^tdetail/(\d+)/$', 'showActivityDetail', {'templateName' : 'microActivityDetailTeacher.html'}),
    )

Code/urls.py
from django.conf.urls import patterns, include, url
import settings
import xadmin

xadmin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('sysuer.urls')),
    url(r'', include('base.urls')),
    url(r'^activity/', include('activity.urls')),
    url(r'^teacher/', include('teacher.urls')),
    url(r'^committee/', include('committee.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^principal/', include('principal.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^weixin/', include('weixin.urls')),
    url(r'^news/', include('activityNews.urls')),
    url(r'^xadmin/', include(xadmin.site.urls)),
    url(r'^(?P<path>.*)$', 'django.views.static.serve', {
        'document_root' : settings.PROJECT_PATH
        }),
    )

Code/activity/models.py
# -*- coding: utf-8 -*-
from django.db import models
from committee.models import Teacher, Societies
from student.models import Student

# Create your models here.

class ActivityManager(models.Manager):
    def credit_sort(self, activity, number):
        registrants = Registrant.objects.filter(activity = activity)
        students = []
        sno = []
        for item in registrants:
            if item.isSelected or item.isMachine:
                continue
            student = Student.objects.get(netid = item.netid)
            student.r_id = item.id
            students.append(student)
        sorted(students, key = lambda x : (x.completeTimes * 1.0 / (x.registTimes + 1)), reverse = True)
        for item in students[:min(number, len(students))]:
            registrant = Registrant.objects.get(id = item.r_id)
            registrant.isMachine = True
            registrant.save()
            activity.nowNumber += 1
            sno.append({'name' : item.name, 'netid' : item.netid})
        activity.save()
        return sno

# *Mark的字段表示该字段是否审批通过
class Activity(models.Model):
    title = models.CharField(max_length = 64)
    titleMark = models.BooleanField(default = True)
    location = models.CharField(max_length = 64)
    locationMark = models.BooleanField(default = True)
    status = models.CharField(max_length = 16, default = 'first',
        choices = (
        ('first', u'第一阶段申请'),
        ('second', u'第二阶段申请'),
        ('success', u'成功'),
        ('ready', u'预审批'),
        ('faild', u'失败'),
        ))
    campus = models.CharField(max_length = 16, choices = (
        ('south', u'南校区'),
        ('east', u'东校区'),
        ('north', u'北校区'),
        ('zhuhai', u'珠海校区'),
        ))
    campusMark = models.BooleanField(default = True)
    type = models.CharField(max_length = 16, choices = (
        ('publicWelfare', u'公益活动'),
        ('nonPublicWelfare', u'非公益活动'),
        ('academic', u'学术活动'),
        ('sport', u'体育活动'),
        ('other', u'其它活动'),
        ('classroom', u'课室申请'),
        ('chair', u'桌椅申请'),
        ('poster', u'张贴申请'),
        ('location', u'校区场地申请'),
        ('actionCenter', u'学生活动中心申请'),
        ('functionRoom', u'校团委功能室申请'),
        ))    
    typeMark = models.BooleanField(default = True)
    academicType = models.CharField(max_length = 16, blank = True, null = True, choices = (
        ('technology', u'科技类'),
        ('culture', u'人文类'),
        ('career', u'职场类'),
        ('internationalCommunication', u'国际交流类'),
        ('newsMedia', u'新闻传播类'),
        ('other', u'其他类'),
        ))    
    academicTypeMark = models.BooleanField(default = True)
    detailType = models.CharField(max_length = 16, blank = True, null = True)
    detailTypeMark = models.BooleanField(default = True)
    sponsor = models.CharField(max_length = 32)
    sponsorMark = models.BooleanField(default = True)
    content = models.TextField()
    contentMark = models.BooleanField(default = True)
    student = models.ForeignKey(Student)
    societies = models.ForeignKey(Societies)
    societiesMark = models.BooleanField(default = True)
    teacher = models.ForeignKey(Teacher)
    teacherMark = models.BooleanField(default = True)
    nowNumber = models.IntegerField(default = 0)
    totalNumber = models.IntegerField(default = 0)
    totalNumberMark = models.BooleanField(default = True)
    deadline = models.DateTimeField(null = True, blank = True)
    deadlineMark = models.BooleanField(default = True)
    startDateTime = models.DateTimeField(null = True, blank = True)
    startDateTimeMark = models.BooleanField(default = True)
    endDateTime = models.DateTimeField(null = True, blank = True)
    endDateTimeMark = models.BooleanField(default = True)
    signDateTime = models.DateTimeField(auto_now_add = True)
    maxTime = models.IntegerField(default = 0)
    maxTimeMark = models.BooleanField(default = True)
    isCompleted = models.BooleanField(default = False)
    isReady = models.BooleanField(default = False)
    firstRemark = models.CharField(max_length = 256, null = True, blank = True)
    secondRemark = models.CharField(max_length = 256, null = True, blank = True)
    objects = ActivityManager()

    def __unicode__(self):
        return self.title + '(活动)'

    class Meta:
        verbose_name = u'公益活动'
        verbose_name_plural = u'公益活动'

class Submission(models.Model):
    description = models.CharField(max_length = 32, null = True, blank = True)
    file = models.FileField(upload_to = 'files', null = True, blank = True)
    type = models.CharField(max_length = 16, choices = (
        ('classroom', u'课室申请'),
        ('chair', u'桌椅申请'),
        ('poster', u'张贴申请'),
        ('location', u'校区场地申请'),
        ('actionCenter', u'学生活动中心申请'),
        ('functionRoom', u'校团委功能室申请'),
        ('car', u'大型车辆进出申请'),
        ))
    startTime = models.DateTimeField(null = True, blank = True)
    endTime = models.DateTimeField(null = True, blank = True)
    location = models.CharField(max_length = 64,
        null = True, blank = True)
    locations = models.ManyToManyField("Location", related_name = "submission")
    number = models.IntegerField(default = 0)
    chairNumber = models.IntegerField(default = 0)
    tentNumber = models.IntegerField(default = 0)
    otherNumber = models.CharField(max_length = 256, null = True, blank = True)
    activity = models.ForeignKey(Activity)
    submissionMark = models.BooleanField(default = True)
    startTimeMark = models.BooleanField(default = True)
    endTimeMark = models.BooleanField(default = True)
    locationMark = models.BooleanField(default = True)
    numberMark = models.BooleanField(default = True)
    chairNumberMark = models.BooleanField(default = True)
    tentNumberMark = models.BooleanField(default = True)
    otherNumberMark = models.BooleanField(default = True)
    hasReturned = models.BooleanField(default = False)

    def __unicode__(self):
        return '申请项 : ' + "self.description"

    class Meta:
        verbose_name = u'申请项'
        verbose_name_plural = u'申请项'

class Attachment(models.Model):
    description = models.CharField(max_length = 256, null = True, blank = True)
    file = models.FileField(upload_to = 'files', null = True, blank = True)
    activity = models.ForeignKey(Activity)
    attachmentMark = models.BooleanField(default = True)

    def __unicode__(self):
        return '附件 : ' + self.description

    class Meta:
        verbose_name = u'附件'
        verbose_name_plural = u'附件'

class Registrant(models.Model):
    netid = models.CharField(max_length = 16)
    activity = models.ForeignKey(Activity)
    registTime = models.DateTimeField(auto_now_add = True)
    isPass = models.BooleanField(default = False)
    isSelected = models.BooleanField(default = False) # manual selsect
    isMachine = models.BooleanField(default = False) # machine select
    isCompleted = models.BooleanField(default = False)
    isStarted = models.BooleanField(default = False)
    startTime = models.DateTimeField(blank = True, null = True)
    endTime = models.DateTimeField(blank = True, null = True)
    time = models.IntegerField(default = 0)

    def __unicode__(self):
        return '参与者 : ' + self.netid

    class Meta:
        verbose_name = u'报名者'
        verbose_name_plural = u'报名者'

class Location(models.Model):
    name = models.CharField(max_length = 64)
    locationid = models.IntegerField(default = 0)
    multiple = models.BooleanField(default = False)
    visible = models.BooleanField(default= True)
    campus = models.CharField(max_length = 16, choices = (
        ('south', u'南校区'),
        ('east', u'东校区'),
        ('north', u'北校区'),
        ('zhuhai', u'珠海校区'),
        ))
    type = models.CharField(max_length = 32, choices = (
        ('classroom', u'课室'),
        ('schoolPlace', u'校区场地0'),
        ('poster', u'宣传场地'),
        ('actionCenter', u'学生活动中心'),
        ('functionRoom', u'校团委功能室申请'),
        ('location', u'校区场地'),
        ))

    def __unicode__(self):
        if self.locationid == 0:
            return '地点 : ' + self.name
        else:
            return '地点 : ' + self.name + " 编号：" + str(self.locationid)

    class Meta:
        verbose_name = u'活动地点'
        verbose_name_plural = u'活动地点'

class Occupation(models.Model):
    location = models.ForeignKey(Location)
    activity = models.ForeignKey(Activity)
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()
    isValid = models.BooleanField(default = True)

    def __unicode__(self):
        return self.activity + ' is using ' + self.location + 'from ' + self.startTime + ' to ' + self.endTime

    class Meta:
        verbose_name = u'占用场地'
        verbose_name_plural = u'占用场地'

class Number(models.Model):
    desk = models.IntegerField(default = 0)
    beachDesk = models.IntegerField(default = 0)
    tent = models.IntegerField(default = 0)
    campus = models.CharField(max_length = 10, choices = (
        ('south', u'南校区'),
        ('east', u'东校区'),
        ('north', u'北校区'),
        ('zhuhai', u'珠海校区'),
        ))
    def __unicode__(self):
        return '校区:' + self.get_campus_display() + ' 资源数量'
    class Meta:
        verbose_name = u'资源数量'
        verbose_name_plural = u'资源数量'

class LimitNumber(models.Model):
    desk = models.IntegerField(default = 0)
    beachDesk = models.IntegerField(default = 0)
    tent = models.IntegerField(default = 0)
    campus = models.CharField(max_length = 10, choices = (
        ('south', u'南校区'),
        ('east', u'东校区'),
        ('north', u'北校区'),
        ('zhuhai', u'珠海校区'),
        ))
    def __unicode__(self):
        return '校区:' + self.get_campus_display() + ' 资源申请限制'
    class Meta:
        verbose_name = u'资源申请限制'
        verbose_name_plural = u'资源申请限制'

Code/activity/templates/microActivityDetail.html
{% extends "microbase.html" %}
{% block titlebar %}活动{% endblock %}
{% block import %}
<link rel="stylesheet" type="text/css" href="/static/css/microActivityDetail.css">
{% endblock %}
{% block content %}
<div data-role="content" id="activityContent" class="innerDiv">
    <dl class="activityItem">
        <dt>{{activity.title}}asdfasdf</dt>
        <dt>
            <dd>公益时长 : {{activity.maxTime}}</dd>
        	<dd>时间 : {{activity.startDateTime|date:"Y-m-d"}} {{activity.startDateTime|time:"H:i"}} 到 {{activity.endtateTime|date:"Y-m-d"}} {{activity.endtateTime|time:"H:i"}}</dd>
        	<dd>地点 : {{activity.location}}</dd>
            <dd>校区 : {{activity.get_campus_display}}</dd>
        	<dd>负责人 : {{activity.student.name}}</dd>
        	<dd>联系方式 : {{activity.student.phone}}</dd>
        	<dd>内容 : <span class="content">{{activity.content | safe}}</span></dd>
            <dd>总人数 : {{activity.totalNumber}}</dd>
            <dd>报名截止时间 : {{activity.deadline|date:"Y-m-d"}} {{activity.deadline|time:"H:i"}}</dd>
        </dt>
        {% ifequal type "student" %}
        <button id="cancelSigning" data-id="{{activity.id}}" class="signOut" name="signOut" {% if isSign %}{% else %}style="display:none;"{% endif %}>取消报名</button>
        <button id="signUp" data-id="{{activity.id}}" class="signIn" name="signIn" {% if isSign %}style="display:none;"{% endif %}>报名</button>
        {% endifequal %}
    </dl>
</div>
{% endblock %}
{% block importjs %}
<script src="/static/js/microActivityDetail.js"></script>
{% endblock %}

Code/activity/templates/microActivityDetailTeacher.html
{% extends "microbase.html" %}
{% block titlebar %}活动详情{% endblock %}
{% block import %}
<link rel="stylesheet" type="text/css" href="/static/css/microActivityDetailTeacher.css">
{% endblock %}
{% block content %}
<div data-role="content">
    <div id="activityItem">
        <dl class="itemBox">
            <dt>名称 : {{activity.title}}</dt>
            <dt>时间 : {{activity.startDateTime|date:"Y-m-d"}} {{activity.startDateTime|time:"H:i"}} 到 {{activity.endDateTime|date:"Y-m-d"}} {{activity.endDateTime|time:"H:i"}}</dt>
            <dt>地点 : {{activity.location}}</dt>
            <dt>负责人 : {{activity.student.name}}</dt>
            <dt>社团 : {{activity.societies.name}}</dt>
            <dt class="itemContent">内容 : {{activity.content | safe}}</dt>
            {% for item in submission %}
            <dt>{{item.get_type_display}}</dt>
            <dt>
                <dd>开始 : {{item.startTime|date:"Y-m-d"}} {{item.startTime|time:"H:i"}}</dd>
                <dd>结束 : {{item.enddime|date:"Y-m-d"}} {{item.enddime|time:"H:i"}}</dd>
                <dd>课室 : {% if item.location %}{{item.location}}{% endif %}</dd>
                <dd>桌子数量 : {% if item.number %}{{item.number}}{% endif %}</dd>
                <dd>椅子数量 : {% if item.chairNumber %}{{item.chairNumber}}{% endif %}</dd>
                <dd>其他物资数量 : {% if item.otherNumber %}{{item.otherNumber}}{% endif %}</dd>
                {% if item.file %}
                <div>
                <a class="btn btn-success halfPass" href="{{item.file.url}}">下载</a>
                </div>
                {% endif %}
            </dt>
            {% endfor %}
            {% for item in attachment %}
            <dt>{{item.description}}</dt>
            <dt>
                <div>
                <a class="btn btn-success halfPass" href="{{item.file.url}}">下载</a>
                </div>
            </dt>
            {% endfor %}
            {% if hasButton %}
            {% ifequal type "committee" %}
            <p>指导老师 <strong>{{activity.teacher.name}}</strong> 意见: {{activity.firstRemark}}</p>
            {% endifequal %}
            <textarea id="remark" placeholder="审批意见/必填"></textarea>
            <div class="operation">
                <a data-toggle="modal" data-target="#confirm"></a>
                <button data-name="pass" class="pass btn btn-success" data-id="{{activity.id}}" ><img src="/static/images/true.png"></button>
                <button data-name= "unpass" class="unpass btn btn-danger" data-id="{{activity.id}}"><img src="/static/images/false.png"></button>
                <button data-name="halfPass" type="button" class="btn btn-warning halfPass" data-id="{{activity.id}}">预审批</button>
            </div>
            {% else %}
            {% if isHalf %}
            {% ifequal type "committee" %}
            <p>指导老师 <strong>{{activity.teacher.name}}</strong> 意见: {{activity.firstRemark}}</p>
            {% endifequal %}
            <textarea id="remark" placeholder="审批意见/必填">{% ifequal type "committee" %}{{activity.secondRemark}}{% else %}{{activity.firstRemark}}{% endifequal %}</textarea>
            <div class="operation">
                <a data-toggle="modal" data-target="#confirm"></a>
                <button data-name="pass" class="pass btn btn-success" data-id="{{activity.id}}" ><img src="/static/images/true.png"></button>
                <button data-name= "unpass" class="unpass btn btn-danger" data-id="{{activity.id}}"><img src="/static/images/false.png"></button>
            </div>
            {% else %}
            {% if isAssesser %}
            {% ifequal type "committee" %}
            <p>指导老师 <strong>{{activity.teacher.name}}</strong> 意见: {{activity.firstRemark}}</p>
            {% endifequal %}
            <textarea id="remark" placeholder="审批意见/必填">{% ifequal type "committee" %}{{activity.secondRemark}}{% else %}{{activity.firstRemark}}{% endifequal %}</textarea>
            <div class="operation">
                <a data-toggle="modal" data-target="#confirm"></a>
                <button data-name="cancel" type="button" class="btn btn-danger halfPass" data-id="{{activity.id}}">取消</button>
            </div>
            {% endif %}
            {% endif %}
            {% endif %}
                    
        </dl>
    </div>  
</div>
{% endblock %}
{% block importjs %}
<script src="/static/js/microActivityDetailTeacher.js"></script>
{% endblock %}

Code/activity/templates/microActivityState.html
{% extends "microbase.html" %}
{% block titlebar %}活动申请状态{% endblock %}
{% block import %}
<link rel="stylesheet" type="text/css" href="/static/css/microActivityState.css">
{% endblock %}
{% block content %}
<div data-role="content" >
    <div class="activityItem">
        {% for item in activities %}
        <dl class="itemBox">
            <dd>名称 : {{item.title}}</dd>
            <dd>开始时间 : {{item.startDateTime|date:"Y-m-d"}} {{item.startDateTime|time:"H:i"}}</dd>
            <dd>结束时间 : {{item.endDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
            <dd>地点 : {{item.location}}</dd>
            <dd>负责人 : {{item.student.name}}</dd>
            <dd>业务指导老师意见 : <span class="smallFont">{% if item.firstRemark %}{{item.firstRemark}}{% else %}(未审批){% endif %}</span></dd>
            <dd>团委老师意见 : <span class="smallFont">{% if item.secondRemark %}{{item.secondRemark}}{% else %}(未审批){% endif %}</span></dd>
            <dd class="state" data-name="state">
                <span class="">{{item.get_status_display}}</span>
            </dd>
        </dl>
        {% empty %}
            <p class="alert">当前没有申请的活动</p>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block importjs %}
<script src="/static/js/microActivityState.js"></script>
{% endblock %}

Code/activity/templates/microApplyedActivity.html
{% extends "microbase.html" %}
{% block titlebar %}已申请的活动{% endblock %}
{% block import %}
<link rel="stylesheet" type="text/css" href="/static/css/microApplyedActivity.css">
{% endblock %}
{% block content %}
<div data-role="header" id="latestHeader">
    <h1>已申请的活动</h1>
</div>
<div data-role="content" id="attendedActivity">
    {% for item in activities %}
    <div class="activityItem" id="activity{{item.id}}">
        <dt>{{item.title}}</dt>
        <dd>{{item.startDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}} 到 {{item.startDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
        <a href="/activity/registrants/{{item.id}}/"><button class="attendedPeople">活动参与者</button></a>
    </div>
    {% empty %}
        <p class="alert">当前没有申请成功的活动</p>
    {% endfor %}
</div>
{% endblock %}
{% block importjs %}
<script src="/static/js/microApplyedActivity.js"></script>
{% endblock %}

Code/activity/templates/microAssessActivity.html
{% extends "microbase.html" %}
{% block titlebar %}审批活动{% endblock %}
{% block import %}
<link rel="stylesheet" type="text/css" href="/static/css/microAssessActivity.css">
{% endblock %}
{% block content %}
<div data-role="header" id="latestHeader">
    <div class="waitToAssess assess">
        <a name="waitToAssess">等待批阅</a>
    </div>
    <div class="assess passAssess">
        <a name="passAssess">通过批阅</a>
    </div>
    <div class="assess personAssess">
        <a name="personAssess">个人通过批阅</a>
    </div>
</div>
<div data-role="content">
    <div class="activityItem">
        <div data-role="collapsible-set" class="personAssessList">
          <div data-role="collapsible">
            <h3>预审批活动</h3>
            {% for item in halfPass %}
            <dl class="itemBox" data-name="personAssess" id="activity{{item.id}}">
                <dd>名称 : {{item.title}}</dd>
                <dd>开始时间 : {{item.startDateTime|date:"Y-m-d"}} {{item.startDateTime|time:"H:i"}}</dd>
                <dd>结束时间 : {{item.endDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
                <dd>申请时间 : {{item.signDateTime|date:"Y-m-d"}} {{item.signDateTime | time:"H:i"}}</dd>
                <dd>地点 : {{item.location}}</dd>
                <dd class="operation">
                    <a class="detail" href="/activity/tdetail/{{item.id}}/"><span>详情</span><span class="img"><img src="/static/images/detail.png"></span></a>
                </dd>
            </dl>
            {% empty %}
            <p class='itemBox mesalert' data-name='personAssess'>当前没有预审批的活动！</p>
            {% endfor %}
          </div>
          <div data-role="collapsible">
            <h3>个人通过活动</h3>
            {% for item in examined %}
            <dl class="itemBox" data-name="personAssess" id="activity{{item.id}}">
                <dd>名称 : {{item.title}}</dd>
                <dd>开始时间 : {{item.startDateTime|date:"Y-m-d"}} {{item.startDateTime|time:"H:i"}}</dd>
                <dd>结束时间 : {{item.endDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
                <dd>申请时间 : {{item.signDateTime|date:"Y-m-d"}} {{item.signDateTime | time:"H:i"}}</dd>
                <dd>地点 : {{item.location}}</dd>
                <dd class="operation">
                    <a class="detail" href="/activity/tdetail/{{item.id}}/"><span>详情</span><span class="img"><img src="/static/images/detail.png"></span></a>
                </dd>
            </dl>
            {% empty %}
            <p class='itemBox mesalert' data-name='waitToAssess'>当前没有个人通过的活动！</p>
            {% endfor %}  
          </div>
        </div>
        {% for item in examining %}
        <dl class="itemBox" data-name="waitToAssess" id="activity{{item.id}}">
            <dd>名称 : {{item.title}}</dd>
            <dd>开始时间 : {{item.startDateTime|date:"Y-m-d"}} {{item.startDateTime|time:"H:i"}}</dd>
            <dd>结束时间 : {{item.endDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
            <dd>申请时间 : {{item.signDateTime|date:"Y-m-d"}} {{item.signDateTime | time:"H:i"}}</dd>
            <dd>地点 : {{item.location}}</dd>
            <dd class="operation">
                <a class="detail" href="/activity/tdetail/{{item.id}}/"><span>详情</span><span class="img"><img src="/static/images/detail.png"></span></a>
            </dd>
        </dl>
        {% empty %}
        <p class='itemBox mesalert' data-name='waitToAssess'>当前已经没有等待批阅的活动了哟！</p>
        {% endfor %}
        {% for item in running %}
        <dl class="itemBox" data-name="passAssess" id="activity{{item.id}}">
            <dd>名称 : {{item.title}}</dd>
            <dd>开始时间 : {{item.startDateTime|date:"Y-m-d"}} {{item.startDateTime|time:"H:i"}}</dd>
            <dd>结束时间 : {{item.endDateTime|date:"Y-m-d"}} {{item.endDateTime|time:"H:i"}}</dd>
            <dd>申请时间 : {{item.signDateTime|date:"Y-m-d"}} {{item.signDateTime | time:"H:i"}}</dd>
            <dd>地点 : {{item.location}}</dd>
            <dd class="operation">
                <a class="detail" href="/activity/tdetail/{{item.id}}/"><span>详情</span><span class="img"><img src="/static/images/detail.png"></span></a>
            </dd>
        </dl>
        {% empty %}
        <p class='itemBox mesalert' data-name='passAssess'>当前还没有通过批阅的活动了哟！</p>
        {% endfor %}
    </div>
</div>

{% endblock %}
{% block importjs %}
<script src="/static/js/microAssessActivity.js"></script>
{% endblock %}